[features]
seeds = false
skip-lint = false
[programs.devnet]
tic_tac_toe = "CzgE1QHdwsigEvPMJXtNHNgEmjKBVhZn3sPHRrU7yKga"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/irenefabris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
